version: '3'

services:
  ocsapplication:
    image: ocsinventory/ocsinventory-docker-image:2.9
    container_name : ocsinventory-server
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "perlcomdata:/etc/ocsinventory-server"
      - "ocsreportsdata:/usr/share/ocsinventory-reports/ocsreports/extensions"
      - "varlibdata:/var/lib/ocsinventory-reports"
      - "httpdconfdata:/etc/httpd/conf.d"
    environment:
      OCS_DB_SERVER: ocsinventory-db
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
      # See documentation to set up SSL for MySQL
      OCS_SSL_ENABLED: 0
    links:
      - ocsdb
    networks:
      - localocs
    depends_on:
      - ocsdb

  ocsdb :
    image : mysql:5.7
    container_name : ocsinventory-db
    restart: always
    ports :
      - 3306:3306
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - sqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : rootpass
      MYSQL_USER : ocsuser
      MYSQL_PASSWORD : ocspass
      MYSQL_DATABASE : ocsweb
    networks:
      - localocs

  ocscron:
    image: ocsinventory/ocsinventory-docker-image:2.9
    container_name : ocsinventory-cron
    restart: always
    command: /usr/bin/cron.sh
    environment:
      OCS_DB_SERVER: ocsinventory-db
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
    links:
      - ocsdb
    networks:
      - localocs
    depends_on:
      - ocsdb

networks:
  localocs:

volumes:
  perlcomdata:
  ocsreportsdata:
  varlibdata:
  httpdconfdata:
  sqldata:

